[package]
name = "rq"
version = "0.1.0"
authors = ["Yábir García <yabirgb@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.39"
serde = {version = "1.0.89", features = ["derive"]}
dirs = "1.0.5"
